cnblog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from blog import views
from cnblog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.login),
    path('index/', views.index),
    path('register/', views.register),
    path('get_validCode_img/', views.get_validCode_img),
    path('logout/', views.logout),
    path('digg/', views.digg),
    path('comment/', views.comment),
    path('comment_tree/', views.comment_tree),
    path('upload/', views.upload),
    # path('upload/', views.add_category),


    # 后台管理页面
    re_path("backend/$", views.backend),
    re_path("backend/add_article/$", views.add_article),
    re_path('backend/del_article/(?P<article_number>\d+)/$', views.del_article),
    re_path('backend/upd_article/(?P<article_number>\d+)/$', views.upd_article),
    re_path('backend/add_category/$', views.add_category),
    re_path('backend/del_category/$', views.del_category),




    # media配置
    re_path(r"media/(?P<path>.*)$", serve,
            {"document_root": settings.MEDIA_ROOT}),
    
    # 个人站点URL
    re_path('^(?P<username>\w+)$', views.home_site),

    # 个人站点内的页面跳转
    # tag category archive跳转
    re_path('^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)$', views.home_site),

    # 文章详情页
    re_path('^(?P<username>\w+)/articles/(?P<article_number>\d+)$', views.article_detail),


]

blog/views.py
# python标准库
import json
import re
from sys import path
from PIL.Image import merge, new
from django import contrib
import threading
import os
from bs4 import BeautifulSoup
from django.db.models.signals import pre_migrate
from django.template.defaultfilters import default, title
from blog import models


# 第三方插件库
from django.db.models.aggregates import Count
from django.shortcuts import redirect, render, HttpResponse
from django.contrib import auth    # 超级用户模块
from django.http import JsonResponse, request, response
from django.db import transaction
from django.db.models.functions import TruncMonth  # 使日期截断至月
from django.db.models import F
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth.decorators import login_required

# 自建库
from .Myforms import UserForm
from blog.utils.validCode import get_valid_code_img
from cnblog import settings

# ---逻辑内容---


def login(request):

    if request.method == 'POST':
        response = {"user": None, "msg": None}  # 响应字典
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")
        valid_code = request.POST.get("valid_code")

        # 验证验证码
        valid_code_str = request.session.get("valid_code_str")
        if valid_code.upper() == valid_code_str.upper():
            # 用户名密码验证
            user = auth.authenticate(username=user, password=pwd)
            if user:
                auth.login(request, user)  # request.user == 当前登录对象
                response["user"] = user.username
                response["msg"] = "log in success!"
            else:
                response["msg"] = "username or password error!"  # 响应信息
        else:
            response["msg"] = "valid code error!"  # 响应信息
        return JsonResponse(response)  # 返回响应字典

    return render(request, 'login.html')


def get_validCode_img(request):
    '''
    获取验证码图片
    '''

    data = get_valid_code_img(request)

    return HttpResponse(data)


def pageinator_bar(request, article_list, article_inside):
    '''
    分页器模块，不是视图
    '''
    try:
        paginator_bar = Paginator(article_list, article_inside)   # paginator对象
        page = int(request.GET.get("page", 1))   # 前端请求的page（号码）
    except EmptyPage as e:
        page = 1

    current_page = paginator_bar.page(page)      # 第page页的数据对象
    count = paginator_bar.count                  # 数据总数
    num_page = paginator_bar.num_pages           # 总页数
    page_range = paginator_bar.page_range        # 页码的列表

    # 保证活跃页面选项居中
    if page < 6:
        page_range = range(1, num_page+1)
    elif page > num_page-5:
        page_range = range(num_page-9,num_page+1)
    else:
        page_range = range(page-4, page+5)

    context = {"article_list": article_list, "page": page, "current_page": current_page, "count": count, "number_page": num_page, "page_range": page_range}

    return context


def index(request):

    article_list = models.Article.objects.all().order_by("-nid")
    context = pageinator_bar(request, article_list, 6)       # context是个字典

    article_hotreading = article_list.order_by("-pageview__pageview_count")[:10] # 热门阅读
    article_hotdiscuss = article_list.order_by("-comment_count")[:10] # 热门阅读
    context["article_hotreading"] = article_hotreading
    context["article_hotdiscuss"] = article_hotdiscuss

    return render(request, 'index.html', context)


def logout(request):

    auth.logout(request)  # request.session.flush()

    return redirect("/index/")


def register(request):
    if request.is_ajax():
        form = UserForm(request.POST)

        response = {"user": None, "msg": None}
        if form.is_valid():
            response["user"] = form.cleaned_data.get("user")

            # 生成一条用户纪录
            user = form.cleaned_data.get("user")
            pwd = form.cleaned_data.get("pwd")
            email = form.cleaned_data.get("email")
            blog_name = request.POST.get("blog_name")
            avatar_obj = request.FILES.get("avatar")

            extra = {}
            # 判断用户有没有上传头像
            if avatar_obj:
                extra["avatar"] = avatar_obj

            # 创建博客
            blog = models.Blog.objects.create(title=blog_name, site_name=user, theme="default.css")
            models.UserInfo.objects.create_user(
                username=user, password=pwd, email=email, blog=blog, **extra)

        else:
            response["msg"] = form.errors

        return JsonResponse(response)

    form = UserForm()

    return render(request, 'register.html', {"form": form})


def get_classication_data(username):
    '''
    分类信息查询模块，不是视图！！
    '''

    user = models.UserInfo.objects.filter(username=username).first()
    blog = user.blog
    article_count_dic = models.Article.objects.filter(user=user).aggregate(c=Count("nid"))
    article_count = article_count_dic.get("c")


    return {"user": user, "blog": blog, "article_count": article_count}


def home_site(request, username, **kwargs):
    '''
    个人站点视图
    '''
    # 判断用户是否存在
    user = models.UserInfo.objects.filter(username=username).first()
    if not user:
        return render(request, '404_notfound.html')
    else:

        # 分类信息查询
        context_classication_data = get_classication_data(username)

        # 获取当前站点的所有文章
        # 基于对象查询
        # article_list = user.article_set.all()
        # 基于__查询，JOIN查询
        article_list = models.Article.objects.filter(user=user).all()

        # 判断是否是跳转

        if kwargs:
            condition = kwargs.get("condition")
            param = kwargs.get("param")
            blog = models.Blog.objects.filter(site_name=username).first()

            if condition == "category":
                article_list = article_list.filter(category__title=param, category__blog=blog).order_by("-nid").all()
            elif condition == "tag":
                print(param)
                article_list = article_list.filter(tags__title=param, tags__blog=blog).order_by("-nid").all()
            elif condition == "archive":
                year, month = param.split("-")
                article_list = article_list.filter(
                    create_time__year=year, create_time__month=month).all()

        # 分页器函数
        context = pageinator_bar(request, article_list, 6)

        context.update(context_classication_data)

        return render(request, "home_site.html", context)


def article_detail(request, username, article_number):
    '''
    文章详情页
    '''
    user = models.UserInfo.objects.filter(username=username).first()
    article = models.Article.objects.filter(
        user=user, nid=article_number).first()
    comments = models.Comment.objects.filter(article=article).all()
    models.PageView.objects.filter(article=article).update(pageview_count=F("pageview_count")+1)

    if not (user and article):
        return render(request, '404_notfound.html')
    else:
        context = get_classication_data(username)
        context["article"] = article
        context["comments"] = comments
        return render(request, 'article_detail.html', context)


def digg(request):
    '''
    点赞视图函数
    '''
    is_up = json.loads(request.POST.get("is_up")) # 将字符串的true&false反序列化成布尔值
    article_number = request.POST.get("article_number")
    user_id = request.user.nid                    # 获取当前登录人的id

    response = {"state":True}  # 构建响应字典

    updown_obj = models.ArticleUpDown.objects.filter(article_id = article_number, user_id=user_id).first()

    if not updown_obj:

        ard = models.ArticleUpDown.objects.create(user_id=user_id, article_id=article_number, is_up=is_up)
        if is_up:
            models.Article.objects.filter(nid=article_number).update(up_count=F("up_count")+1)
        else:
            models.Article.objects.filter(nid=article_number).update(down_count=F("down_count")+1)
    else:

        response["state"] = False
        response["handled"] = updown_obj.is_up

    return JsonResponse(response)

def comment(request):
    '''
    评论视图函数(包含邮件发送)
    '''
    response = {}

    if request.is_ajax():
        user = request.user
        content = request.POST.get("content")
        article_number = request.POST.get("article_number")
        parent_comment_id = request.POST.get("parent_comment_id")

        article = models.Article.objects.filter(nid=article_number).first()

        # 事务操作
        with transaction.atomic():
            comment_obj = models.Comment.objects.create(content=content, article_id=article_number, user=user, parent_comment_id=parent_comment_id)
            models.Article.objects.filter(nid=article_number).update(comment_count=F("comment_count")+1)

        response["create_time"] = comment_obj.create_time.strftime("%Y-%m-%d %X")
        response["username"] = request.user.username
        response["content"] = content
        if parent_comment_id:
            parent_comment_obj = comment_obj.parent_comment
            response["parent_comment_user"] = parent_comment_obj.user.username
            response["parent_comment_content"] = parent_comment_obj.content

        # # 异步发送邮件

        # subject = "您的文章%s新增了一条评论内容，请查看"%article.title
        # message = content
        # from_email = settings.EMAIL_HOST_USER
        # recipient_list = [article.user.email]

        # threading.Thread(target=send_mail, args=(
        #     subject, message, from_email, recipient_list,
        # ))

        return JsonResponse(response)

def comment_tree(request):
    '''
    评论树视图函数
    '''
    if request.is_ajax():
        article_number = request.POST.get("article_number")
        comments = list(models.Comment.objects.filter(article_id=article_number).values_list(
            "nid", "user__username", "content", "parent_comment_id" ))
        return JsonResponse(comments, safe=False)

@login_required
def backend(request):
    '''
    后台管理页面
    '''
    username = request.user.username
    context_classication_data = get_classication_data(username)  # blog user article_count

templates/404_notfound.html
<h1>404 not found</h1>

templates/article_detail.html
{% extends 'base.html' %}

{% block content %}

<link rel="stylesheet" href="/static/css/article_detail.css">

{% csrf_token %}

<!-- 文章标题 -->
<div>
    <h3 class="text-center">{{article.title}}</h3>
</div>
<!-- 文章信息 -->
<div class="article_info">
    <span>发布于：{{article.create_time|date:"Y-m-d"}}</span>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span>访问量：{{article.pageview.pageview_count}}</span>
</div>
<hr>
<!-- 文章内容 -->
<div class="content" style="margin: 40px 30px;">
    {{article.content|safe}}
</div>
<hr>

<!-- 点赞 -->
<div class="clearfix">
    <div id="div_digg">
        <div class="diggit action">
            <span class="diggnum" id="digg_count">{{article.up_count}}</span>
        </div>
        <div class="buryit action">
            <span class="burynum" id="bury_count">{{article.down_count}}</span>
        </div>
        <div class="clear"></div>
        <div class="diggword" id="digg_tips"></div>
    </div>
</div>

<!-- 评论区（评论树） -->
<div class="comments_area_tree">
    <div style="margin: 10px 0 10px 0;">评论树 共有({{article.comment_count}})条评论</div>

</div>

<!-- 评论区（评论楼） -->
<!-- <div class="comments_area">
    <div style="margin-bottom: 10px;">评论列表</div>
    <ul class="list-group comment_list">
        {% for comment in comments %}
        <li class="list-group-item">
            <div>
                <a href=""># {{forloop.counter}}楼</a> &nbsp;&nbsp;
                {{comment.create_time|date:"Y-m-d H:i"}} &nbsp;&nbsp;
                <a href="/{{comment.user}}">{{comment.user}}</a>
                <a class="pull-right reply_btn" username="{{comment.user}}" comment_id="{{comment.nid}}">回复</a>
            </div>
            {% if comment.parent_comment_id %}
            <div class="well">
                {{comment.parent_comment.user}}：{{comment.parent_comment.content}}
            </div>
            {% endif %}
            <div style="margin: 17px 0 17px 5px;">{{comment.content}}</div>
        </li>
        {% endfor%}
    </ul>
</div> -->

<!-- 发表评论 -->
<div class="comments">
    <div style="margin-bottom: 10px;">
        <span id="commentform_title">发表评论</span>
        <span class="pull-right">
            当前登录用户：<img id="user_now" src="/media/{{request.user.avatar}}">{{request.user.username}}
        </span>
    </div>
    <textarea parent_comment_id="" name="" id="comment_content" cols="30" rows="10" class="comment_area"></textarea>
    <input type="button" value="提交评论" class="pull-right comment_btn">
    <span id="comment_msg" class="pull-right"></span>

</div>

<script>
    // 点赞请求
    $(".action").click(function () {
        var is_up = $(this).hasClass("diggit");

        $obj = $(this).children("span")

        $.ajax({
            url: "/digg/",
            type: "post",
            data: {
                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                "is_up": is_up,
                "article_number": "{{article.nid}}",
            },
            success: function (data) {
                if (!data.state) {

                    var val = data.handled ? "您已经推荐过了" : "您已经反对了";
                    $("#digg_tips").html(val);

                } else {

                    var val = parseInt($obj.text());
                    $obj.text(val + 1);

                }
            },
        })

        setTimeout(function () {
            $("#digg_tips").html("");
        }, 2000)

    })

    // 评论上传
    $(".comment_btn").click(function () {
        var content = $(".comment_area").val();
        var parent_comment_id = $(".comment_area").attr("parent_comment_id");
        if (content) {
            $.ajax({

                url: "/comment/",
                type: "post",
                data: {
                    "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                    "article_number": "{{article.nid}}",
                    "content": content,
                    "parent_comment_id": parent_comment_id,
                },
                success: function (data) {

                    var create_time = data.create_time;
                    var username = data.username;
                    var content = data.content;
                    var parent_comment_user = data.parent_comment_user;
                    var parent_comment_content = data.parent_comment_content;

                    if (parent_comment_id) {
                        var comment_ajax = `
                            <li class="list-group-item">
                                <div>
                                    <a href=""># 本楼</a> &nbsp;&nbsp;
                                    ${create_time} &nbsp;&nbsp;
                                    <a href="/${username}">${username}</a>
                                </div>
                                <div style="margin: 17px 0 17px 5px;">${content}</div>
                            </li>`
                            ;
                        // 显示评论
                        $("[comment_tree_id="+parent_comment_id+"]").parent().parent().append(comment_ajax);
                    } else {
                        var comment_ajax = `
                            <li class="list-group-item">
                                <div>
                                    <a href=""># 本楼</a> &nbsp;&nbsp;
                                    ${create_time} &nbsp;&nbsp;
                                    <a href="/${username}">${username}</a>
                                </div>
                                <div style="margin: 17px 0 17px 5px;">${content}</div>
                            </li>`
                            ;
                        $(".comments_area_tree").append(comment_ajax);    
                    }



                    // 成功信息提示
                    $("#comment_msg").removeClass("comment_msg_fail");
                    $("#comment_msg").addClass("comment_msg_pass");
                    $("#comment_msg").html("提交评论成功");

                    // 评论内容区清空
                    $("#comment_content").val("")
                },
            })
        } else {

            $("#comment_msg").removeClass("comment_msg_pass");
            $("#comment_msg").addClass("comment_msg_fail");
            $("#comment_msg").html("请输入内容");

        }

        setTimeout(function () {
            $("#comment_msg").html("");
        }, 2000)

    })

    // 回复按钮事件
    $(".comments_area_tree").on('click', '.reply_btn', function () {
        $("#comment_content").focus();
        var comment_id = $(this).attr("comment_tree_id");
        console.log(comment_id)
        var p_name = $(this).attr("username");
        var val = "@" + p_name + '\n';
        $("#comment_content").val(val);
        $("#comment_content").attr("parent_comment_id", comment_id);
    })

    // 评论树显示
    $.ajax({
        url: "/comment_tree/",
        type: "post",
        data: {
            "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
            "article_number": "{{article.nid}}",
        },
        success: function (comments) {
            var counter = 1

            var create_comment_tree = function create_comment_tree(comments, flag) {

                        $.each(comments, function (index, comment) {
                        var nid = comment[0];
                        var username = comment[1];
                        var content = comment[2];
                        var parent_comment_id = comment[3];

                        var s = `
                            <div class="list-group-item">
                                <div>
                                    <a href=""># ${counter}楼</a> &nbsp;&nbsp;
                                    <a href="/${username}">${username}</a>
                                    <a class="pull-right reply_btn" username="${username}" comment_tree_id=${nid}>回复</a>
                                </div>
                                <div style="margin: 17px 0 17px 5px;">${content}</div>
                            </div>
                            `;

                        if (!parent_comment_id && flag) {
                            $(".comments_area_tree").append(s);
                            counter++;
                        }
                        if (parent_comment_id && !flag) {
                            $("[comment_tree_id=" + parent_comment_id + "]").parent().parent().append(s);  // 这个地方太妙了
                        }
                    }
                )
                
            }

            create_comment_tree(comments, flag=1);
            create_comment_tree(comments, flag=0);

        },
    })


</script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/static/blog/icon/v_icon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="/static/blog/icon/v_icon.png" type="image/x-icon"/>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <script src="\static\js\jquery.js"></script>
    <script src="\static\js\bootstrap.min.js"></script>
    <script src="\static\js\jquery-3.2.1.min.js"></script>
    <style>
        /* 导航栏 */
        .header {
            width: 100%;
            height: 60px;
            background-color: #369;
        }

        .header .title {
            font-size: 18px;
            font-weight: 100;
            line-height: 60px;
            color: white;
        }

        .backend {
            float: right;
            color: white;
            font-size: 14px;
            margin-right: 10px;
        }

        .title_dropdown {
            min-width: 60px;
        }

        .title_content {
            margin-left: 45px;
        }

        /* 个人首页内容 */
        .content_container {
            margin: 20px 20px 0px 20px;
        }

        .article_info {
            color: grey;
        }

        #direct_select {
            margin: 15px 45px 0px 0px;
        }

        .info_window {
            text-align: center;
        }   
    </style>
    <title>{{blog.title}}</title>
</head>

<body>
    <!-- 以下是站头 -->
    <div class="header">
        <div class="content">
            <div class="title">
                <span class="title_content">
                    {{blog.title}}
                </span>
                <div class="btn-group backend" id="direct_select">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                        <span class="glyphicon glyphicon-user"></span> {{request.user.username}} <span class="caret"></span>
                    </button>
                    <ul class="title_dropdown dropdown-menu">
                      <li><a href="/"><span class="glyphicon glyphicon-globe"></span> 主站首页</a></li>
                      <li><a href="/{{user.username}}/backend/"><span class="glyphicon glyphicon-wrench"></span> 后台管理</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="/logout/"><span class="glyphicon glyphicon-log-out"></span> 注销</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- 以下是个人站点内容 -->
    <div class="container-fluid content_container">
        <div class="row">
            <!-- 左侧信息栏内容 -->
            <!-- 个人信息+分类+标签+年月归档 -->
            <div class="col-md-2 info_window">

                {% load my_tags %}
                {% get_classification_style user %}

            </div>
            <!-- 文章列表 -->
            <div class="col-md-8">
                {% block content %}

                {% endblock %}
            </div>
            <!-- 右侧功能栏 -->
            <div class="col-md-2">

                <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">
                          title
                      </h3>
                    </div>
                    <div class="panel-body">
                      content
                    </div>
                </div>

            </div>
            
        </div>
    </div>



</body>

<script>
    $(function() {
        var date = new Date()
        var year = date.getFullYear();
    })
</script>

</html>

templates/classfication.html
<div>
    <!-- 个人信息 -->
    <div class="panel panel-default personal-info">
        <div class="panel-body">
            个人信息
        </div>
        <div class="panel-footer">
            <!-- 头像 -->
            <div>
                <img width="90" height="90" src="media/{{user.avatar}}" alt="">
            </div>
            <div style="margin-top: 10px;">
                <div>
                    <span style="margin-right: 20px;">文章总数：{{article_count}}</span>
                </div>
                <div>
                    <span>注册日期：{{user.create_time|date:"Y-m"}}</span>
                </div>
            </div>

        </div>
    </div>
    <!-- 分类 -->
    <div class="panel panel-default category">
        <div class="panel-body">
            分类
        </div>
        <div class="panel-footer">
            {% for category in category_list %}
            <div>
                <a href="/{{user.username}}/category/{{category.0}}">{{category.0}} ({{category.1}})</a>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- 标签 -->
    <div class="panel panel-default">
        <div class="panel-body">
            标签
        </div>
        <div class="panel-footer">
            {% for tag in tag_list %}
            <div>
                <a href="/{{user.username}}/tag/{{tag.0}}">{{tag.0}} ({{tag.1}})</a>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- 年月归档 -->
    <div class="panel panel-default">
        <div class="panel-body">
            年月归档
        </div>
        <div class="panel-footer">
            {% for date in date_list %}
            <div>
                <a href="/{{user.username}}/archive/{{date.0|date:'Y-m'}}">{{date.0|date:"Y-m"}} ({{date.1}})</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/home_site.html
{% extends 'base.html' %}

{% block content %}

<style>
    .article_info {
        margin-left: 15px;
    }
    
    /* 选择器CSS */
    #pagination_bar {
        text-align: center;
    }
</style>

    {% for article in current_page %}
    <div class="panel panel-default">
        <!-- 标题 -->
        <div class="panel-heading">
            <a href="/{{article.user}}/articles/{{article.nid}}" class="article_title">{{article.title}}</a>
        </div>
        <!-- 内容 -->
        <div class="panel-body article-desc">
            <span class="simple_content">
                {{article.desc}}
            </span>
        </div>
        <!-- 文章信息 -->
        <div class="article_info">
            <span style="margin-right: 20px;">
                <a href="/{{article.user.username}}">{{article.user.username}}</a>
            </span>
            <span style="margin-right: 20px;">
                发布于：{{article.create_time|date:"Y-m-d H:i"}}
            </span>
            <span style="margin-right: 20px;">
                <span class="glyphicon glyphicon-comment"></span>
                {{article.comment_count}}
            </span>
            <span style="margin-right: 20px;">
                <span class="glyphicon glyphicon-thumbs-up"></span>
                {{article.up_count}}
            </span>
            <span style="margin-right: 20px;">
                <span class="glyphicon glyphicon-thumbs-down"></span>
                {{article.down_count}}
            </span>
            <span style="margin-right: 20px;">
                <span class="glyphicon glyphicon-eye-open"></span>
                {{article.pageview.pageview_count}}
              </span>
        </div>
    </div>
    {% endfor %}

    <!-- 下面是分页器功能 -->
    {% include "paginator.html" %}

{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        #avatar {
            display: none;
        }

        #avatar_img {
            margin-left: 20px;
        }

        .error {
            color: red;
        }
    </style>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <title>register</title>
</head>

<body>
    <h3>注册页面</h3>
    <div class="container">
        <div class="col-md-6 col-lg-offset-3">

            <form>
                {% csrf_token %}
                {% for filed in form %}

                <div class="form-group">
                    <!-- auto_id是自动填写每一个id值 -->
                    <label for="{{filed.auto_id}}">{{filed.label}}</label>
                    {{filed}}
                    <span class="error pull-right"></span>
                </div>

                {% endfor %}
                <!-- 博客名称 -->
                <div class="form-group">
                    <label for="blog_name">博客名称</label>
                    <input type="text" id="blog_name" name="blog_name" class="form-control">
                </div>

                <!-- 头像 -->
                <div class="form-group">
                    <label for="avatar">
                        头像
                        <img id="avatar_img" width="60" height="60" src="/static/blog/img/default.jpg" alt="">
                    </label>
                    <input id="avatar" type="file">
                </div>

                <input href="" type="button" value="确认注册" class="btn btn-default pull-right reg_btn">

            </form>
        </div>
    </div>

    <script src="\static\js\jquery-3.2.1.min.js"></script>

    <script>
        // 捕捉id=avatar的元素的内容改变的动作
        $("#avatar").change(function () {
            // 获取用户选中的文件对象
            var file_obj = $(this)[0].files[0];
            // 获取文件对象的路径，文件路径保存到了reader.result中
            var reader = new FileReader();
            reader.readAsDataURL(file_obj);
            // 修改id = avatar_img元素的src属性
            // 等待reader读完再执行修改元素的函数
            reader.onload = function () {
                $("#avatar_img").attr("src", reader.result);
            }
        })

        // 基于Ajax提交数据
        $(".reg_btn").click(function () {
            var formdata = new FormData();
            formdata.append("user", $("#id_user").val());
            formdata.append("pwd", $("#id_pwd").val());
            formdata.append("re_pwd", $("#id_re_pwd").val());
            formdata.append("email", $("#id_email").val());
            formdata.append("blog_name", $("#blog_name").val());
            formdata.append("csrfmiddlewaretoken", '{{csrf_token}}');
            formdata.append("avatar", $("#avatar")[0].files[0]);

            $.ajax({
                url: "",
                type: "post",
                // 发送FormData对象必须加上的两行命令
                contentType: false,
                // 序列化data的内容
                processData: false,
                // 构建form-code的对象
                data: formdata,
                success: function (data) {
                    if (data.user) {
                        // 注册成功时
                        location.href = '/login/'
                    }
                    else {
                        // 注册失败时
                        // 循环打印错误信息
                        $(".error").html("");
                        $(".error").parent().removeClass("has-error");
                        $.each(data.msg, function (filed, error_list) {
                            if (filed == "__all__") {
                                $("#id_re_pwd").next().html(error_list[0]).parent().addClass("has-error");
                            }
                            $("#id_" + filed).next().html(error_list[0]);
                            $("#id_" + filed).parent().addClass("has-error");
                        })
                    }
                }
            })
        })
    </script>

</body>

</html>